# Индивидуальное задание

In [22]:
# импорт библиотек
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [23]:
# Загрузка данных с ценами на ноутбуки и их характеристиками
data = pd.read_csv('./Laptop-Price.csv')
data.head()

Company          Product   TypeName  Inches             ScreenResolution  \
0      HP           250 G6   Notebook    15.6            Full HD 1920x1080   
1    Acer         Aspire 3   Notebook    15.6                     1366x768   
2    Asus  ZenBook UX430UN  Ultrabook    14.0            Full HD 1920x1080   
3    Acer          Swift 3  Ultrabook    14.0  IPS Panel Full HD 1920x1080   
4      HP           250 G6   Notebook    15.6                     1366x768   

    Ram       OpSys Cpu Brand       Cpu Model Cpu Rate  SSD  HDD  \
0   8GB       No OS     Intel   Core i5 7200U   2.5GHz  256    0   
1   4GB  Windows 10       AMD  A9-Series 9420     3GHz    0  500   
2  16GB  Windows 10     Intel   Core i7 8550U   1.8GHz  512    0   
3   8GB  Windows 10     Intel   Core i5 8250U   1.6GHz  256    0   
4   4GB       No OS     Intel   Core i5 7200U   2.5GHz    0  500   

   Flash Storage  Hybrid Gpu Brand         Gpu Model  Unnamed: 16  Price_euros  
0              0       0     Intel   HD Graphics 620          NaN        575.0  
1              0       0       AMD         Radeon R5          NaN        400.0  
2              0       0    Nvidia     GeForce MX150          NaN       1495.0  
3              0       0     Intel  UHD Graphics 620          NaN        770.0  
4              0       0     Intel   HD Graphics 620          NaN        393.9

In [20]:
# визуализация
data.describe()

Inches          SSD          HDD  Flash Storage       Hybrid  \
count  1146.000000  1146.000000  1146.000000    1146.000000  1146.000000   
mean     15.151396   187.710297    46.347295       1.898778     0.539267   
std       1.319303   160.313927   144.192738      26.275202    15.035060   
min      11.300000     0.000000     0.000000       0.000000     0.000000   
25%      14.000000     0.000000     0.000000       0.000000     0.000000   
50%      15.600000   256.000000     0.000000       0.000000     0.000000   
75%      15.600000   256.000000     1.000000       0.000000     0.000000   
max      18.400000   512.000000   500.000000     512.000000   508.000000   

       Unnamed: 16  Price_euros  
count          0.0  1146.000000  
mean           NaN  1204.876972  
std            NaN   676.630847  
min            NaN   265.000000  
25%            NaN   699.750000  
50%            NaN  1049.750000  
75%            NaN  1535.000000  
max            NaN  6099.000000

In [30]:
# Обработка категориальных данных
categorical_features = [
  'Company',
  'Product',
  'TypeName',
  'OpSys',
  'Cpu Brand',
  'Gpu Brand',
  'ScreenResolution',
  'Cpu Model',
  'Gpu Model',
]

from sklearn.preprocessing import LabelEncoder

data['Ram'] = data['Ram'].astype(str).str.replace('GB', '', regex=False)
data['Cpu Rate'] = data['Cpu Rate'].astype(str).str.replace('GHz', '', regex=False)

for feature in categorical_features:
  labelencoder = LabelEncoder()
  data[feature] = labelencoder.fit_transform(data[feature])

data.head()

Company  Product  TypeName  Inches  ScreenResolution Ram  OpSys  Cpu Brand  \
0        6       46         3    15.6                 7   8      3          1   
1        0       52         3    15.6                 0   4      4          0   
2        2      517         4    14.0                 7  16      4          1   
3        0      370         4    14.0                14   8      4          1   
4        6       46         3    15.6                 0   4      3          1   

   Cpu Model Cpu Rate  SSD  HDD  Flash Storage  Hybrid  Gpu Brand  Gpu Model  \
0         30      2.5  256    0              0       0          1         49   
1         11        3    0  500              0       0          0         74   
2         53      1.8  512    0              0       0          2         38   
3         37      1.6  256    0              0       0          1         95   
4         30      2.5    0  500              0       0          1         49   

   Unnamed: 16  Price_euros  
0          NaN        575.0  
1          NaN        400.0  
2          NaN       1495.0  
3          NaN        770.0  
4          NaN        393.9

In [37]:
# Обработка пропущенных значений
from sklearn.impute import SimpleImputer

X = data.drop('Price_euros', axis=1)
y = data['Price_euros']

imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

print(X_imputed)

[[6.000e+00 4.600e+01 3.000e+00 ... 1.000e+00 4.900e+01 5.750e+02]
 [0.000e+00 5.200e+01 3.000e+00 ... 0.000e+00 7.400e+01 4.000e+02]
 [2.000e+00 5.170e+02 4.000e+00 ... 2.000e+00 3.800e+01 1.495e+03]
 ...
 [9.000e+00 4.910e+02 0.000e+00 ... 1.000e+00 4.400e+01 6.380e+02]
 [9.000e+00 4.990e+02 0.000e+00 ... 1.000e+00 4.400e+01 1.499e+03]
 [6.000e+00 1.000e+00 3.000e+00 ... 0.000e+00 7.800e+01 7.640e+02]]


In [38]:
# разделение данных на тестовые и тренировочные
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)